// <copyright file="RedirectService.cs" company="Moonrise Software, LLC">
// Copyright (c) Moonrise Software, LLC. All rights reserved.
// Licensed under the MIT License (https://opensource.org/licenses/MIT)
// See https://github.com/CWALabs/SkyCMS
// for more information concerning the license and the contributors participating to this project.
// </copyright>

namespace Sky.Editor.Services.Redirects
{
    using Cosmos.Common.Data;
    using Cosmos.Common.Data.Logic;
    using Microsoft.EntityFrameworkCore;
    using Sky.Editor.Infrastructure.Time;
    using Sky.Editor.Services.Publishing;
    using Sky.Editor.Services.Slugs;
    using System;
    using System.Text;
    using System.Threading.Tasks;

    /// <summary>
    /// Implements redirect management by storing redirects as special <see cref="Article"/> records (StatusCode = Redirect).
    /// </summary>
    public sealed class RedirectService : IRedirectService
    {
        private readonly ApplicationDbContext db;
        private readonly ISlugService slugs;
        private readonly IClock clock;
        private readonly IPublishingService publishedArtifactService;

        /// <summary>
        /// Initializes a new instance of the <see cref="RedirectService"/> class.
        /// </summary>
        /// <param name="db">EF Core database context.</param>
        /// <param name="slugs">Slug normalization service.</param>
        /// <param name="clock">Clock abstraction for consistent timestamps.</param>
        /// <param name="publishedArtifactService">Published artifact service.</param>
        public RedirectService(ApplicationDbContext db, ISlugService slugs, IClock clock, IPublishingService publishedArtifactService)
        {
            this.db = db;
            this.slugs = slugs;
            this.clock = clock;
            this.publishedArtifactService = publishedArtifactService;
        }

        /// <inheritdoc/>
        public async Task<Article> CreateOrUpdateRedirectAsync(string fromSlug, string toSlug, Guid userId)
        {
            fromSlug = slugs.Normalize(fromSlug);
            toSlug = slugs.Normalize(toSlug);

            // Do not redirect from root; silently ignore.
            if (fromSlug == "root")
            {
                return null;
            }

            // Check if a redirect from this fromSlug already exists
            var existingRedirect = await db.Articles
                .FirstOrDefaultAsync(a =>
                    a.UrlPath == fromSlug.TrimEnd('/') &&
                    a.StatusCode == (int)StatusCodeEnum.Redirect);

            if (existingRedirect != null)
            {
                // Update the existing redirect to point to the new target
                existingRedirect.RedirectTarget = toSlug;
                existingRedirect.Updated = clock.UtcNow;

                // Update the redirect JavaScript and content
                var redirectJavaScript = new StringBuilder();
                redirectJavaScript.AppendLine("<script type=\"text/javascript\">");
                redirectJavaScript.AppendLine("  // Redirect script");
                redirectJavaScript.AppendLine("  window.location.href = '" + System.Net.WebUtility.HtmlEncode(toSlug) + "';");
                redirectJavaScript.AppendLine("</script>");
                redirectJavaScript.AppendLine("<noscript>");
                redirectJavaScript.AppendLine("<meta http-equiv=\"refresh\" content=\"0; url='" + System.Net.WebUtility.HtmlEncode(toSlug) + "'\" />");
                redirectJavaScript.AppendLine("</noscript>");

                var pageBody = new StringBuilder();
                pageBody.AppendLine("<h1>Redirecting to " + System.Net.WebUtility.HtmlEncode(toSlug) + "</h1>");
                pageBody.AppendLine("<p>If you are not redirected, click <a href=\"/" + System.Net.WebUtility.HtmlEncode(toSlug) + "\">here</a>.</p>");
                pageBody.AppendLine("<p>Redirect generated by SkyCMS.</p>");

                existingRedirect.HeaderJavaScript = redirectJavaScript.ToString();
                existingRedirect.Content = pageBody.ToString();

                await db.SaveChangesAsync();
                await publishedArtifactService.PublishAsync(existingRedirect);
                return existingRedirect;
            }

            // Allocate a new redirect article (new article number sequence entry).
            // Find the maximum article number from both Articles and ArticleNumbers tables
            var maxArticleNumber = 1; // Start at 1 (root article uses 1 by convention)

            // Check the maximum from existing articles
            if (await db.Articles.AnyAsync())
            {
                var maxFromArticles = await db.Articles.MaxAsync(a => a.ArticleNumber);
                maxArticleNumber = Math.Max(maxArticleNumber, maxFromArticles);
            }

            // Check the maximum from ArticleNumbers tracking table
            if (await db.ArticleNumbers.AnyAsync())
            {
                var maxFromArticleNumbers = await db.ArticleNumbers.MaxAsync(a => a.LastNumber);
                maxArticleNumber = Math.Max(maxArticleNumber, maxFromArticleNumbers);
            }

            // Increment to get the next available number
            maxArticleNumber++;

            var redirectJavaScript2 = new StringBuilder();
            redirectJavaScript2.AppendLine("<script type=\"text/javascript\">");
            redirectJavaScript2.AppendLine("  // Redirect script");
            redirectJavaScript2.AppendLine("  window.location.href = '" + System.Net.WebUtility.HtmlEncode(toSlug) + "';");
            redirectJavaScript2.AppendLine("</script>");
            redirectJavaScript2.AppendLine("<noscript>");
            redirectJavaScript2.AppendLine("<meta http-equiv=\"refresh\" content=\"0; url='" + System.Net.WebUtility.HtmlEncode(toSlug) + "'\" />");
            redirectJavaScript2.AppendLine("</noscript>");

            var pageBody2 = new StringBuilder();
            pageBody2.AppendLine("<h1>Redirecting to " + System.Net.WebUtility.HtmlEncode(toSlug) + "</h1>");
            pageBody2.AppendLine("<p>If you are not redirected, click <a href=\"/" + System.Net.WebUtility.HtmlEncode(toSlug) + "\">here</a>.</p>");
            pageBody2.AppendLine("<p>Redirect generated by SkyCMS.</p>");

            var redirect = new Article
            {
                Id = Guid.NewGuid(),
                HeaderJavaScript = redirectJavaScript2.ToString(),
                ArticleNumber = maxArticleNumber,
                StatusCode = (int)StatusCodeEnum.Redirect,
                UrlPath = fromSlug.TrimEnd('/'),
                Title = fromSlug,
                Content = pageBody2.ToString(),
                Published = clock.UtcNow,
                Updated = clock.UtcNow,
                VersionNumber = 1,
                UserId = userId.ToString(),
                BannerImage = string.Empty,
                RedirectTarget = toSlug
            };

            db.Articles.Add(redirect);
            db.ArticleNumbers.Add(new ArticleNumber { LastNumber = redirect.ArticleNumber });
            await db.SaveChangesAsync();
            await publishedArtifactService.PublishAsync(redirect);
            return redirect;
        }
    }
}
