services:
  sky.editor:
    image: ${DOCKER_REGISTRY-}sky-editor
    volumes:
      - ${SKYCMS_EDITOR_DATA_PATH:-./.data/editor}:/data/skycms
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Optional: if your app uses an env var for DB path
      - SKYCMS_DB_PATH=/data/skycms/
    build:
      context: .
      dockerfile: Editor/Dockerfile

  sky.publisher:
    image: ${DOCKER_REGISTRY-}sky-publisher
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${SKYCMS_PUBLISHER_DATA_PATH:-./.data/publisher}:/data/skycms
    build:
      context: .
      dockerfile: Publisher/Dockerfile
