<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<RazorLangVersion>Latest</RazorLangVersion>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Common\Cosmos.Common.csproj" />
	</ItemGroup>



</Project>
