<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Company>Moonrise Software LLC</Company>
		<Version>12.4.0</Version>
		<AssemblyVersion>12.4.0</AssemblyVersion>
		<FileVersion>12.4.0</FileVersion>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<RepositoryUrl></RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryType>git</RepositoryType>
		<PackageTags>Microsoft Graph, Cosmos CMS</PackageTags>
		<Description>This provices Microsoft Graph utilities for Cosmos CMS.</Description>
		<PackageProjectUrl></PackageProjectUrl>
		<PackageReleaseNotes>Documentation dependencies updated.</PackageReleaseNotes>
		<Title>Microsoft Graph Utilities for Cosmos</Title>
		<Copyright>Copyright 2024 (c) Moonrise Software, LLC.</Copyright>
		<NoWarn>NU5104</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" pack="true" PackagePath="." />
	</ItemGroup>

	<PropertyGroup>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="stylecop.json" />
		<None Remove="stylecop.json" />
		<AdditionalFiles Include="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Graph.Beta" />
		<PackageReference Include="Microsoft.Kiota.Abstractions" />
		<PackageReference Include="Microsoft.Kiota.Authentication.Azure" />
		<PackageReference Include="Microsoft.Kiota.Http.HttpClientLibrary" />
		<PackageReference Include="Microsoft.Kiota.Serialization.Form" />
		<PackageReference Include="Microsoft.Kiota.Serialization.Json" />
		<PackageReference Include="Microsoft.Kiota.Serialization.Multipart" />
		<PackageReference Include="Microsoft.Kiota.Serialization.Text" />
		<PackageReference Include="Microsoft.Graph.Core" />

		<PackageReference Include="StyleCop.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="System.Configuration.ConfigurationManager" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="README.md">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </None>
	</ItemGroup>

</Project>
