<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<UserSecretsId>aspnet-CDT.Cosmos.Cms-7EA5716F-3AA0-40C0-B742-C20FE7803177</UserSecretsId>
		<AnalysisLevel>latest</AnalysisLevel>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<RepositoryUrl>https://github.com/CosmosSoftware/CosmosCms</RepositoryUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<Version>9.3.0.1</Version>
		<AssemblyVersion>9.3.0.1</AssemblyVersion>
		<FileVersion>9.3.0.1</FileVersion>
		<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
		<Authors></Authors>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<SignAssembly>False</SignAssembly>
		<EnableSdkContainerSupport>true</EnableSdkContainerSupport>
		<DockerfileContext>..\..\..</DockerfileContext>
	</PropertyGroup>
	
	<ItemGroup>
		<InternalsVisibleTo Include="Sky.Tests" />
	</ItemGroup>

	<PropertyGroup>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
		<EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
		<ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:9.0</ContainerBaseImage>
		<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="C:\Users\toiya\.nuget\packages\cdt.cosmos.cms.common\2021.6.23.6\contentFiles\any\net5.0\Views\CCMS_Examples\Index.cshtml" />
	  <Content Remove="C:\Users\toiya\.nuget\packages\cdt.cosmos.cms.common\2021.6.23.6\contentFiles\any\net5.0\Views\CCMS_Examples\TextFile1.txt" />
	  <Content Remove="C:\Users\toiya\.nuget\packages\cdt.cosmos.cms.common\2021.6.23.6\contentFiles\any\net5.0\Views\CCMS_Examples\_CosmosLayout.cshtml" />
	  <Content Remove="C:\Users\toiya\.nuget\packages\cosmos.cms.common\7.0.0.10\contentFiles\any\net6.0\Views\CCMS_Examples\Index.cshtml" />
	  <Content Remove="C:\Users\toiya\.nuget\packages\cosmos.cms.common\7.0.0.10\contentFiles\any\net6.0\Views\CCMS_Examples\TextFile1.txt" />
	  <Content Remove="C:\Users\toiya\.nuget\packages\cosmos.cms.common\7.0.0.10\contentFiles\any\net6.0\Views\CCMS_Examples\_CosmosLayout.cshtml" />
	  <Content Remove="stylecop.json" />
	  <Content Remove="wwwroot\css\sky-blog.css" />
	  <Content Remove="wwwroot\images\samples\134038968578143524.jpg" />
	  <Content Remove="wwwroot\images\samples\20250917_OHR.YoungMoose_EN-US2991221135_UHD_bing.jpg" />
	  <Content Remove="wwwroot\images\samples\20250920_OHR.OktoberfestSwing_EN-US7916182497_UHD_bing.jpg" />
	  <Content Remove="wwwroot\images\samples\20250921_OHR.IceOtters_EN-US7982442590_UHD_bing.jpg" />
	  <Content Remove="wwwroot\images\samples\20250924_OHR.BearLodge_EN-US9061134971_UHD_bing.jpg" />
	  <Content Remove="wwwroot\images\samples\20250926_OHR.AutumnChipmunk_EN-US9248345602_UHD_bing.jpg" />
	  <Content Remove="wwwroot\images\samples\20251015_OHR.AmethystLaccaria_EN-US0640413961_UHD_bing.jpg" />
	  <Content Remove="wwwroot\images\skycms\SkyCMSLogoDarkBackground.jpeg" />
	  <Content Remove="wwwroot\images\skycms\SkyCMSLogoLightBackground.jpeg" />
	  <Content Remove="wwwroot\js\blog-stream-loader.js" />
	  <Content Remove="wwwroot\js\editors\editorCore.js" />
	  <Content Remove="wwwroot\js\editors\JavaScript - Copy (2).js" />
	  <Content Remove="wwwroot\js\editors\JavaScript - Copy (3).js" />
	  <Content Remove="wwwroot\js\editors\JavaScript - Copy.js" />
	  <Content Remove="wwwroot\js\editors\JavaScript.js" />
	  <Content Remove="wwwroot\js\editors\monaco-editor-core.js" />
	  <Content Remove="wwwroot\js\editors\monaco-editor-insert-helpers.js" />
	  <Content Remove="wwwroot\js\setup-sensitive-fields.js" />
	  <Content Remove="wwwroot\lib\cosmos\ckeditor\ckeditor-widget.301.js" />
	</ItemGroup>

	<ItemGroup>
	  <AdditionalFiles Include="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Views\Templates\EditCode.cshtml" />
	  <None Include="Views\Templates\Index.cshtml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.ResourceManager" />
		<PackageReference Include="Azure.ResourceManager.Cdn" />
		<PackageReference Include="BCrypt.Net-Next" />
		<PackageReference Include="CsvHelper" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
		<PackageReference Include="PasswordGenerator" />
		<PackageReference Include="RestSharp" />
		<PackageReference Include="SixLabors.ImageSharp" />
		<PackageReference Include="MimeTypeMapOfficial" />
		<PackageReference Include="Roslynator.Analyzers">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="StyleCop.Analyzers">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Data.SqlClient" />
		<PackageReference Include="System.Drawing.Common" />
		<PackageReference Include="System.Private.Uri" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Common\Cosmos.Common.csproj" />
	  <ProjectReference Include="..\Cosmos.EmailServices\Cosmos.EmailServices.csproj" />
	  <ProjectReference Include="..\Sky.Cms.Api.Shared\Sky.Cms.Api.Shared.csproj" />
	  <ProjectReference Include="..\Sky.Shared.Razor\Sky.Shared.Razor.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <ContainerPort Include="8081" />
	</ItemGroup>
	
	<ItemGroup>
		<EmbeddedResource Include="Templates\**\*.html" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="wwwroot\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	
	<ItemGroup>
	  <Compile Remove="Services\BlogPublishing\**" />
	  <Content Remove="Services\BlogPublishing\**" />
	  <EmbeddedResource Remove="Services\BlogPublishing\**" />
	  <None Remove="Services\BlogPublishing\**" />
	</ItemGroup>
	
	<ItemGroup>
	  <Folder Include="Services\Migrations\Testing\" />
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio>
			<UserProperties libman_1json__JsonSchema="" />
		</VisualStudio>
	</ProjectExtensions>


</Project>
