// <auto-generated />
using System;
using Cosmos.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Sky.Editor.Data.Migrations.MySql
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250122000000_AddLuceneSearchEntities_MySql")]
    partial class AddLuceneSearchEntities_MySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a placeholder for the target model
            // The actual model builder configuration will be automatically generated
            // when the migration is properly created through EF Core tools
        }
    }
}