<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Company>Moonrise Software LLC</Company>
		<Version>9.3.0.1</Version>
		<AssemblyVersion>9.3.0.1</AssemblyVersion>
		<FileVersion>9.3.0.1</FileVersion>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<RepositoryUrl>https://github.com/MoonriseSoftwareCalifornia/Cosmos.EmailServices</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>SMTP, SendGrid, Azure Email, Email Provider, Identity, ASP.NET Identity</PackageTags>
		<Description>This is a SendGrid, SMTP, and Azure Communications Email Provider for ASP.NET Core Identity.</Description>
		<PackageProjectUrl>https://github.com/MoonriseSoftwareCalifornia/CosmosCMS</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotes>Documentation dependencies updated.</PackageReleaseNotes>
		<Title>Cosmos CMS Email Services</Title>
		<Copyright>Copyright 2023 (c) Moonrise Software, LLC.</Copyright>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="stylecop.json" />
	</ItemGroup>

	<PropertyGroup>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<PackageIcon>B2C_BrandIcon_Black.png</PackageIcon>
		<IncludeSymbols>True</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="B2C_BrandIcon_Black.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Azure.Communication.Email" />
	  <PackageReference Include="Azure.Identity" />
	  <PackageReference Include="HtmlAgilityPack" />
	  <PackageReference Include="Roslynator.Analyzers">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
	  <PackageReference Include="Microsoft.Extensions.Logging" />
	  <PackageReference Include="SendGrid" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Templates\EmailTemplates.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>EmailTemplates.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Templates\EmailTemplates.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>EmailTemplates.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Update="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
