using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Cosmos.BlobService;
using MediatR;
using MimeTypes;
using SkyCMS.Drivers.ElFinder.Adapters;
using SkyCMS.Drivers.ElFinder.Commands;
using SkyCMS.Drivers.ElFinder.Responses;

namespace SkyCMS.Drivers.ElFinder.Handlers;

/// <summary>
/// Handles the "duplicate" command.
/// Copies each target into its own parent directory with a non-colliding name
/// generated by appending "~" before the extension (e.g. logo~.png).
/// See Docs/commands/duplicate.md.
/// </summary>
public class DuplicateCommandHandler : IRequestHandler<DuplicateCommand, IElFinderResponse>
{
    private readonly IElFinderStorageAdapter _adapter;

    public DuplicateCommandHandler(IElFinderStorageAdapter adapter)
    {
        _adapter = adapter ?? throw new ArgumentNullException(nameof(adapter));
    }

    public async Task<IElFinderResponse> Handle(DuplicateCommand request, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.Targets))
        {
            return ElFinderErrorResponse.InvalidParams("Targets are required");
        }

        var response = new DuplicateResponse();

        var hashes = request.Targets.Split(',', StringSplitOptions.RemoveEmptyEntries);
        foreach (var hash in hashes)
        {
            var sourcePath = _adapter.DecodePath(hash.Trim());
            if (sourcePath == null)
            {
                continue;
            }

            // Resolve entry once; covers accessibility check and provides name/type metadata.
            var sourceEntry = await _adapter.GetEntryAsync(sourcePath, cancellationToken);
            if (sourceEntry == null)
            {
                continue;
            }

            var parentPath = GetParentPath(sourcePath);
            var copyName = await BuildCopyNameAsync(parentPath, sourcePath, cancellationToken);
            var destPath = parentPath.TrimEnd('/') + "/" + copyName;

            var copied = await _adapter.CopyAsync(sourcePath, destPath, cancellationToken);
            if (copied == null)
            {
                continue;
            }

            var hash2 = _adapter.EncodePath(destPath);
            var phash = _adapter.EncodePath(parentPath);

            response.Added.Add(new ElFinderObject
            {
                Hash = hash2,
                PHash = phash,
                Name = copyName,
                Size = copied.Size,
                Mime = copied.IsDirectory ? "directory" : GetMimeType(copyName),
                Ts = new DateTimeOffset(copied.Modified).ToUnixTimeSeconds(),
                Read = 1,
                Write = 1,
                Locked = 0,
                Dirs = copied.IsDirectory ? 1 : 0,
            });
        }

        return response;
    }

    private async Task<string> BuildCopyNameAsync(string parentPath, string sourcePath, CancellationToken cancellationToken)
    {
        var entries = await _adapter.GetEntriesAsync(parentPath, cancellationToken);
        var existingNames = new System.Collections.Generic.HashSet<string>(
            System.Linq.Enumerable.Select(entries, e => e.Name ?? string.Empty),
            StringComparer.OrdinalIgnoreCase);

        var originalName = Path.GetFileName(sourcePath.TrimEnd('/'));
        var ext = Path.GetExtension(originalName);
        var baseName = Path.GetFileNameWithoutExtension(originalName);

        var candidate = baseName + "~" + ext;
        var i = 1;
        while (existingNames.Contains(candidate))
        {
            candidate = baseName + "~" + i + ext;
            i++;
        }

        return candidate;
    }

    private static string GetParentPath(string path)
    {
        var trimmed = path.TrimEnd('/');
        var slash = trimmed.LastIndexOf('/');
        return slash >= 0 ? trimmed[..(slash + 1)] : "/";
    }

    private static string GetMimeType(string fileName)
    {
        try
        {
            return MimeTypeMap.GetMimeType(Path.GetExtension(fileName));
        }
        catch
        {
            return "application/octet-stream";
        }
    }
}
